version: '3.8'

services:
  lightin-up-utah:
    build: .
    container_name: lightin-up-utah-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - WORKERS=4
      - MEMORY_THRESHOLD=400
      - MAX_MEMORY_PER_WORKER=512
      - ENABLE_COMPRESSION=true
      - ENABLE_MONITORING=true
      - MONITORING_INTERVAL=30000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    networks:
      - app-network

  # Optional: Nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: lightin-up-utah-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - lightin-up-utah
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 